# To opt out of the system crypto-policies configuration of krb5, remove the
# symlink at /etc/krb5.conf.d/crypto-policies which will not be recreated.
# includedir /etc/krb5.conf.d/

[logging]
    default = FILE:/var/log/krb5libs.log
    kdc = FILE:/var/log/krb5kdc.log
    admin_server = FILE:/var/log/kadmind.log

[libdefaults]
    dns_lookup_realm = false
    dns_lookup_kdc = true
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true
    rdns = false
    pkinit_anchors = FILE:/etc/pki/tls/certs/ca-bundle.crt
    spake_preauth_groups = edwards25519
    qualify_shortname = ""
#    default_realm = DOUBLEDOUBLEU.COM
#    default_ccache_name = KEYRING:persistent:%{uid}

[realms]
DOUBLEDOUBLEU.COM = {
    kdc = creativity.doubledoubleu.com
    kdc = intuition.doubledoubleu.com
    admin_server = creativity.doubledoubleu.com
    master_kdc = creativity.doubledoubleu.com
    default_domain = doubledoubleu.com
}

[domain_realm]
.doubledoubleu.com = DOUBLEDOUBLEU.COM
doubledoubleu.com = DOUBLEDOUBLEU.COM
